default: &default
  adapter: postgresql
  template: template0
  username: uvindex
  password: uvindex1234
  host: localhost
  port: 5432
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: uvindex_development

test:
  <<: *default
  database: uvindex_test

production:
  <<: *default
  database: uvindex_production
  username: uvindex
  password: <%= ENV['UVINDEX_DATABASE_PASSWORD'] %>
